### PR TITLE
autopki + scripts route-uip and client-connect

### PR DESCRIPTION
**Pull request by dennybaa**
Hi there,

we've been using your cookbook in our production, thanks for a good cookbook.
I've refactored it a bit and introduced AutoPKI, automatic generation of client certificates without data_bag usage.
If you like this functionality you are welcome to merge it.

Regrads,
Dennis

### CODE REVIEW

**Comment by cmur2** [comment]
Thank you! Nice to hear that I'm not the only one using this ;-)
Many changes, it'll take some time to merge them and maybe I won't pick all of them but thanks anyways!

**Comment by dennybaa** [comment]
You are welcome!

Yeah, you can have a look at it) The semantics of the prior code are not touched though, just it feels like cookbook needs refactoring. Maybe my work on the code refactoring is not the best. But I just think it might be helpful.
Btw we managed to make VPN mesh between 2 datacenters with the new code and autopki seems to be a nice idea)

Cheers.

**Comment by cmur2** [comment]
Nice! I didn't even know that autopki exists but seems reasonable - I'll definitely have a look into it. For the refactoring part you're definitely right...

Out of interest: do you use this with Chef 11?

**Comment by dennybaa** [comment]
AutoPKI it's kinda my invention, but I took pkitool code from the opscode cookbook. That's how autopki appeared. Since we've got so many nodes and managing so many keys through data bags would be completely exhausting.
Yeah, we are using only chef11.

**Pull request closed without merging**
